import re
s = 'AAATATATTGACAGATGAGATTGAAAGGACAAGAAAGTATATGCCCTTTTGAGGTCACCTTCTTCAATCAAAGAGGCTCCTAGTTTCCTCTGTTCCCATGGAACCTAAGGGCCCAAATCATCATCAACTACAGGTGCCCTCTTTCTTGAATCCTCCACAAAAAGCAAGCATGCCAGAGAACAACATCAACAACCATAACAAGCAGCCT'
pattern = re.compile('[ATGC]{21}[Gg]{2}')
items = re.finditer(pattern,s)
for item in items:
    print(item.span())
    print('>')
    print(item.group())
    print(item)
